version: "3"

services:
  kindred_db:
    container_name: kindred_db
    image: kindred_db
    build:
      context: kindred_db
    expose:
      - 5432
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  kindred_app:
    container_name: kindred_app
    image: kindred_app
    build:
      context: .
      dockerfile: kindred_app.Dockerfile
    volumes:
      - webroot:/var/www/html
    depends_on:
      - kindred_db
    environment:
      DBHOST: kindred_db
    expose:
      - 9000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  kindred_webserver:
    container_name: kindred_webserver
    image: nginx:alpine
    volumes:
      - webroot:/var/www/html
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

volumes:
     webroot:
